# Generated by Django 4.2.1 on 2023-08-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("agent", "Agent"),
                    ("manager", "Manager"),
                    ("customer", "Customer"),
                ],
                default="agent",
                max_length=20,
            ),
        ),
    ]
