# Generated by Django 4.2.1 on 2023-08-07 13:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="sender_user",
            new_name="sent_by",
        ),
    ]
