# Generated by Django 4.2.1 on 2023-08-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_rename_sender_user_message_sent_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="sent_by",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
