# Generated by Django 4.2.1 on 2023-08-07 13:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_alter_message_sent_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="receiver_user",
            new_name="created_by",
        ),
    ]
