# Generated by Django 4.2.1 on 2023-08-08 06:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_rename_receiver_user_message_created_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="message",
            new_name="messages",
        ),
    ]
