name: Chatapplication-CI

on:
  push:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        sudo apt-get install libpq-dev -y
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Apply Migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate
        pwd
    - name: Run Tests
      run: |
        python manage.py test
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}

  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
    - name: testing the script
      run: python --version
